name: mycrm
description: A Demo app for sip intergration for mycrm llc.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  bloc: ^8.1.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  fpdart: ^0.5.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  go_router: ^6.2.0
  injectable: ^2.1.0
  json_annotation: ^4.8.0
  shared_preferences: ^2.0.18
  sip_ua: ^0.5.5

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  injectable_generator: ^2.1.4

flutter:
  uses-material-design: true

scripts:
  build: fvm flutter pub run build_runner build --delete-conflicting-outputs
  watch: fvm flutter pub run build_runner watch
